### ISSUE TITLE
why is this deprecated ?

### ISSUE THREAD

**Issue by weepy** [szensk/subllualove#11]
?

**Comment by szensk** [comment]
I don't use SublimeText or Love2D any more. You are free to fork it.

**Comment by npinochet** [comment]
Is this still true? It's been updated recently and I don't know if I should use this package or not.

**Comment by szensk** [comment]
@npinochet It should be updated due to the work of @Aiq0 
Give it a shot and let me know if it works.

**Comment by npinochet** [comment]
@szensk It does! Thank you for updating the repo's description.
