### ISSUE TITLE
IndexError in ST4113

### ISSUE THREAD

**Issue by iamiota** [szensk/subllualove#15]
This library is great, thanks!
I get errors when I use it in sublime text 4, any suggestions?

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 928, in on_modified_async
    run_view_callbacks('on_modified_async', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 708, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/Users/1/Library/Application Support/Sublime Text 3/Packages/Lua Love/Main.py", line 90, in on_modified_async
    if self.ST >= 3000 and self.onchange(view):
  File "/Users/1/Library/Application Support/Sublime Text 3/Packages/Lua Love/Main.py", line 78, in onchange
    if 'source.lua.love' not in self.scope_regex.findall(view.scope_name(view.sel()[-1].b)) and (not filename or not filename.endswith('.lua')):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime.py", line 1017, in __getitem__
    raise IndexError()
IndexError```

**Comment by Aiq0** [comment]
I'll look into this after school

**Comment by szensk** [comment]
Can reproduce by calling view.sel().clear() before:
`
>>> scope_regex.findall(view.scope_name(view.sel()[-1].b))
['source.lua.love']
>>> view.sel().clear()
>>> scope_regex.findall(view.scope_name(view.sel()[-1].b))
Traceback (most recent call last):
  File "__main__", line 1, in <module>
  File "C:\Program Files\Sublime Text\Lib\python38\sublime.py", line 1054, in __getitem__
    raise IndexError()
IndexError
`

As a workaround, check if len(view.sel()) > 0?

**Comment by Aiq0** [comment]
What you are doing when this error occurs? As the error occurs when selection is empty and view is changed, but I cannot get view changed without selection not being empty (Correct me please, if I am wrong)

But I can think of these solutions:
1. if `len(view.sel()) == 0` use some other text point (like `0` - beginning of the file) instead of current selection, else do it in unchanged way
2. Use `view.syntax().scope`, but this is only available from Sublime Text build 4081
3. Something like:
```diff
diff --git a/Main.py b/Main.py
index 6a3199f..97258c0 100755
--- a/Main.py
+++ b/Main.py
@@ -75,7 +75,7 @@ class ParseLuaCommand(sublime_plugin.EventListener):
 			return False
 		filename = view.file_name()
 
-		if 'source.lua.love' not in self.scope_regex.findall(view.scope_name(view.sel()[-1].b)) and (not filename or not filename.endswith('.lua')):
+		if ST >= 4081 and ('source.lua.love' not in view.syntax().scope) or ('source.lua.love' not in self.scope_regex.findall(len(view.sel()) > 0 and view.scope_name(view.sel()[-1].b) or 1)) and (not filename or not filename.endswith('.lua')):
 			view.erase_regions('lua')
 			return False
```
4. Any other suggestions?

**Comment by szensk** [comment]
@Aiq0 3 looks good to me. But since the line is really long should getting the scope be a separate method?
Then the if is smaller 
```
if 'source.lua.love' not in self.scope_regex.findall(self.get_scope()) and (not filename or not filename.endswith('.lua')):
```

**Comment by Aiq0** [comment]
Yeah, it is really long...

Is this better? (if it is OK now, then I will push the changes along with new release)
```diff
diff --git a/Main.py b/Main.py
index 6a3199f..81fdfe3 100755
--- a/Main.py
+++ b/Main.py
@@ -70,12 +70,15 @@ class ParseLuaCommand(sublime_plugin.EventListener):
 
 	pending = 0
 
+	def get_scope(self, view):
+		return len(view.sel()) > 0 and view.scope_name(view.sel()[-1].b) or 1
+
 	def onchange(self, view):
 		if not settings.get('live_parser', True):
 			return False
 		filename = view.file_name()
 
-		if 'source.lua.love' not in self.scope_regex.findall(view.scope_name(view.sel()[-1].b)) and (not filename or not filename.endswith('.lua')):
+		if self.ST >= 4081 and 'source.lua.love' not in view.syntax().scope or 'source.lua.love' not in self.scope_regex.findall(self.get_scope(view)) and (not filename or not filename.endswith('.lua')):
 			view.erase_regions('lua')
 			return False
```

**Comment by szensk** [comment]
That looks much better (after your latest edit). 👍

**Comment by Aiq0** [comment]
@iamiota, Can you please test the master branch (see Manual installation in readme), if it works now? If yes, I'll publish new release

**Comment by iamiota** [comment]
@szensk @Aiq0 Thank you guys, I will test in the afternoon.

**Comment by iamiota** [comment]
@Aiq0 It works! thank you!

**Comment by Aiq0** [comment]
Ok, I'll create new release, when I get home
