### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by skwerlman** [szensk/subllualove#7]
I want to use this as a base for a syntax highlighter for [TUG](nerdkingdom.com), but I'm not sure if I can, since there's no license specified.
Can I use this code as a base, and if I can, how should I credit you? (links, comments, etc)

**Comment by szensk** [comment]
I wouldn't credit me. I'd credit https://github.com/rorydriscoll/LuaSublime since most of it is based directly on that (with a few additions for Love2D functions). It's under an MIT license.
