### ISSUE TITLE
Ctrl+B won't open love.exe

### ISSUE THREAD

**Issue by AnastasiaDunbar** [szensk/subllualove#9]
I use Windows 8 64-bit. My executable is at `C:\Program Files\LOVE\love.exe`.
And I try to run a file named `main.lua` in a folder with Sublime Text 2.
Pressing Ctrl+B, nothing will appear but Build Results with no information.
I also get this in the status bar.
![error](https://cloud.githubusercontent.com/assets/11806048/14149352/10a4e15a-f6a4-11e5-9a78-f2661ca34fcc.png)

**Comment by szensk** [comment]
Is lua installed on your machine and available on your system path? If not, disable the parser with `"live_parser": false".

Secondly, from the readme, ctrl+b doesn't launch the project in love. It is, however, available with the command palette. You can change this in the `LuaLove.sublime-build` file. 

Finally, I stopped using this plugin myself as I switched to another editor (vim). It is no longer maintained. For example it doesn't know the new Love 0.10 functions.

**Comment by AnastasiaDunbar** [comment]
I installed Lua, still nothing.
Here's what happened.
`'love' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by szensk** [comment]
Love 2D needs to be on your path.

**Comment by AnastasiaDunbar** [comment]
Where exactly, where my projects are?
